version: '3.8'

services:
  web:
    build:
      context: ./proiect1
      dockerfile: Dockerfile.prod
    command: gunicorn proiect1.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./proiect1/.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./proiect1/.env.prod.db

volumes:
  postgres_data:

