version: '3.8'

services:
  web:
    build: ./proiect1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./proiect1/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./proiect1/.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=chat_db
    ports:
      - 5432:5432

volumes:
  postgres_data:
