# Generated by Django 4.1.2 on 2022-12-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesaj',
            old_name='question_text',
            new_name='msg_text',
        ),
        migrations.AlterField(
            model_name='mesaj',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
