# Generated by Django 4.1.2 on 2022-12-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0003_rename_image_mesaj_msg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesaj',
            name='msg_image',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
    ]
